### ISSUE TITLE
Style Command Palette

### ISSUE THREAD

**Issue by gadenbuie** [gadenbuie/rsthemes#26]
- [command palette](https://github.com/rstudio/rstudio/blob/master/src/gwt/src/org/rstudio/studio/client/application/ui/CommandPalette.ui.xml)
- [command palette entries](https://github.com/rstudio/rstudio/blob/master/src/gwt/src/org/rstudio/studio/client/application/ui/CommandPaletteEntry.ui.xml)

<details><summary>Sketch</summary>

```css
#rstudio_command_palette_search,
#rstudio_command_palette_list [id*="rstudio_command_"],
input#rstudio_command_palette_search {
  background-color: purple;
}

.rstudio-themes-flat .rstudio-themes-border {
  border-color: purple;
}

.rstudio-themes-flat .gwt-PopupPanel .popupContent #rstudio_command_palette_list [id*="rstudio_command_"] table .gwt-Label,
.rstudio-themes-flat .gwt-PopupPanel .popupContent #rstudio_command_palette_list [id*="rstudio_command_"] table td {
  background-color: blue;
  color: red;
}

.rstudio-themes-flat .gwt-PopupPanel .popupContent #rstudio_command_palette_list [aria-selected="true"],
.rstudio-themes-flat .gwt-PopupPanel .popupContent #rstudio_command_palette_list [aria-selected="true"] table .gwt-Label {
  background-color: green;
}

.rstudio-themes-flat .gwt-PopupPanel .popupContent #rstudio_command_palette_list [id*="rstudio_command_"]:hover,
.rstudio-themes-flat .gwt-PopupPanel .popupContent #rstudio_command_palette_list [id*="rstudio_command_"]:hover table .gwt-Label,
.rstudio-themes-flat .gwt-PopupPanel .popupContent #rstudio_command_palette_list [id*="rstudio_command_"]:hover table td {
  background-color: limegreen;
}

input#rstudio_command_palette_search {
  margin: -15px;
  padding: 15px;
  width: 600px;
  border-color: purple;
}
```

</details>
