### ISSUE TITLE
Style job pane progress bar

### ISSUE THREAD

**Issue by gadenbuie** [gadenbuie/rsthemes#27]
```css
.rstheme_toolbarWrapper [role="progressbar"] > div {
  background-color: pink;
}
```
