### ISSUE TITLE
Style search results file name

### ISSUE THREAD

**Issue by gadenbuie** [gadenbuie/rsthemes#36]
```css
#rstudio_workbench_panel_find_in_files td[colspan="2"] {
  color: #addb67;
}
```
